site_name: {{ cookiecutter.project_name }}
repo_url: https://github.com/{{ cookiecutter.github_username }}/{{ cookiecutter.project_slug }}

theme:
  name: material

nav:
  - Introduction: 'index.md'
  - api_docs.md

markdown_extensions:
  - pymdownx.snippets:
      check_paths: true

plugins:
  - search:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: true
      watch:
        - src/{{ cookiecutter.package_name }}
