name: Draft a release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version number (e.g. 1.2.3) OR one of: patch|minor|major|prepatch|preminor|premajor|prerelease'
        required: true
        default: 'patch'
{% raw %}
jobs:
  draft-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install
      - name: Update version
        run: poetry version ${{ github.event.inputs.version }}
      - name: Update changelog
        id: changelog
        run: |
          poetry run kacl-cli release ${{ github.event.inputs.version }} --modify --auto-link
          echo "" >> CHANGELOG.md
          body=$(poetry run kacl-cli get ${{ github.event.inputs.version }})
          body="${body//'%'/'%25'}"
          body="${body//$'\n'/'%0A'}"
          body="${body//$'\r'/'%0D'}"
          echo ::set-output name=body::$body
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          add: 'CHANGELOG.md pyproject.toml'
          branch: 'master'
          message: 'Release ${{ github.event.inputs.version }}'
      - name: Create tag
        run: |
          git tag ${{ github.event.inputs.version }}
          git push origin ${{ github.event.inputs.version }}
      - name: Create a draft release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.version }}
          release_name: Release ${{ github.event.inputs.version }}
          body: ${{ steps.changelog.outputs.body }}
          draft: true{% endraw %}
